---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Naming/VariableNumber:
  Exclude:
  - lib/eac_rest/response.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/lib/eac_rest/api_spec.rb
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
